name = "TPSA"
uuid = "dbf3670b-7870-4525-844b-ea5ede5f6926"
authors = ["Matt Signorelli"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
